name: test
description: Shows what two movies have in common
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  omdb_dart: 0.0.2
  tint: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
